// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Calculator
{
	public partial class GraphViewController : UIViewController
	{
		public GraphViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
