// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using LinqToTwitter;
using UIKit;

namespace Smashtag
{
	public partial class MetaDataTableViewController : UITableViewController
	{
		public MetaDataTableViewController (IntPtr handle) : base (handle)
		{
		}

		private Status _tweet;
		public Status Tweet
		{
			get { return _tweet; }
			set { _tweet = value; SetupUI();  }
		}

		void SetupUI()
		{
			Title = Tweet.User.ScreenNameResponse;
		}

}
}
