// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Smashtag
{
	public partial class TweetImageViewCell : UITableViewCell
	{
		public TweetImageViewCell (IntPtr handle) : base (handle)
		{
		}

		public void SetImage(string url)
		{

			if (!String.IsNullOrEmpty(url))
			{
				var imageData = NSData.FromUrl(new Uri(url));
				tweetImageView.Image = new UIImage(imageData);
				tweetImageView.ContentMode = UIViewContentMode.ScaleAspectFit;
				//tweetImageView.SizeToFit();
			}
		}
	}
}
